name: Upload Pre-release

on:
  push:
    branches:
      main

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  upload-prerelease:
    name: Upload Pre-release
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build x86
      run: msbuild /m /p:Platform=x86 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build x64
      run: msbuild /m /p:Platform=x64 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Move and Rename x86 Binary
      run: mv Release/InduceBlueScreen.exe InduceBlueScreen-x86.exe
      
    - name: Move and Rename x64 Binary
      run: mv x64/Release/InduceBlueScreen.exe InduceBlueScreen-x64.exe
    
    - name: Upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          title: Development Build
          files: |
            LICENSE
            InduceBluescreen-x86.exe
            InduceBluescreen-x64.exe
